FROM mhart/alpine-node:10 as builder

WORKDIR /app

COPY package*.json ./

# move tmp directory and install package.json
RUN npm install

# es6를 사용하기 위한 babel설정
COPY ./.babelrc ./
COPY . .
EXPOSE 8080
RUN npm run build

FROM nginx:1.13.9-alpine
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

COPY --from=builder /app/index.html /usr/share/nginx/html/index.html
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# CMD는 명령어를 배열 형태로 배치하며 실제로 앱을 실행시키는 커맨드가 들어간다.
# CMD ["npm", "run", "dev"]
