export {default as Home} from './home/home';
export {default as Report} from './report/report';
export {default as Dashboard} from './dashboard/dashboard';
export {default as Info} from './info/info';
export {default as SignUp} from './signup/signup';
export {default as SignIn} from './signin/signin';
export {default as Subscribing} from './subscribing/subscriptions';
export {default as SubscribingInfo} from './subscribingInfo/subscribingInfo';
export {default as Recommend} from './recommend/recommend';
