//  user
export const GET_SUBS = 'GET_SUBS';
export const GET_USERS_SUBSTMPL_LIST = 'GET_USERS_SUBSTMPL_LIST';

// auth
export const AUTH_LOGIN_TRY = 'AUTH_LOGIN_TRY';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const USER_INITIALLIZE = 'USER_INITIALLIZE';
