//  user
export const GET_SUBS = 'GET_SUBS';
export const INSERT_SUBSCRIPTIONS = 'INSERT_SUBSCRIPTIONS';
export const GET_USERS_SUBSTMPL_LIST = 'GET_USERS_SUBSTMPL_LIST';
export const DELETE_TEMP_SUBSCRIPTIONS = 'DELETE_TEMP_SUBSCRIPTIONS';

// auth
export const AUTH_LOGIN_TRY = 'AUTH_LOGIN_TRY';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const USER_INITIALLIZE = 'USER_INITIALLIZE';
